### ISSUE TITLE
How to provide background material

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/sa4ss#1]
Decide how to provide background material because the ftp site is not always accessible to readers, especially once the STAR panel is over.

- Create an appendix
- Provide links to them
- Pull all information out into the main document

**Comment by chantelwetzel-noaa** [comment]
Based on discussion between Kelli and I, currently, we are opting to present the background documentation in an appendix.  The texts for the appendix will be developed into an Rmarkdown file and can be added easily to an assessment via a child process.  This decision was driven by the 'living' nature of the document which may need to be updated each assessment cycle depending upon non-standard sampling issues (i.e. potential lack of all surveys in 2020).
