### ISSUE TITLE
francis_data_2011 citation should not have hilborn as an author

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/sa4ss#103]
## **Problem**
ss4ss.bib lists Ray Hilborn as a coauthor on the francis_data_2011 citation. [He was not an author](https://cdnsciencepub.com/doi/full/10.1139/f2011-025), but was the associate editor.

## **Proposal**
Remove him from the author list for future cycles

**Comment by iantaylor-NOAA** [comment]
This is a routine problem for CJFAS citations. @methot_adjusting_2011 in sa4ss.bib is also wrong (Yong Chen was associated editor, not co-author).

What's the best solution, should we issue pull requests for stuff like this when we find them or just circle back after assessment season and cleanup and add/subtract citations based on the season's findings?

**Comment by kellijohnson-NOAA** [comment]
It would be nice if others got the benefit of fixed errors during a cycle so I prefer knowing when something wrong is found so I can fix it and let everyone know. Though, I do wish to use [journals](https://github.com/nmfs-fish-tools/journals) next time for the journal articles where are know that there are very few errors in the .bib files. But that is for a different issue/discussion thread.
