### ISSUE TITLE
Disclaimer Location

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/sa4ss#11]
For draft documents we need to add the disclaimer:

_These materials do not constitute a formal publication and are for information only. They are in a pre-review, pre-decisional state and should not be formally cited {or reproduced}. They are to be considered provisional and do not represent any determination or policy of NOAA or the Department of Commerce._

 I wanted to open an issue for us to discuss where to put the disclaimer. My initial thought would be to have the disclaimer in the middle of the second page where currently the copyright and citation is located.  Thoughts?

**Comment by kellijohnson-NOAA** [comment]
I worry that people don't actually read the second page, and therefore, I think we should put it on the first page.

**Comment by kellijohnson-NOAA** [comment]
Do we want a draft watermark as well? I am not sure how "fancy" we want to go, but I figured it if is just a discussion here, then skies the limit.

**Comment by iantaylor-NOAA** [comment]
I think a draft watermark would be ambiguous and potentially distracting.
I do think it would be useful to have options or user-defined text
describing what version of the document it is, like "Pre-review draft",
"Post-review draft" which could then be removed for the final submission.
This could go on the first page above the data and the disclaimer (which I
also support putting on page 1).
But all that would be a low priority.

**Comment by mkapur** [comment]
I struggled to include a disclaimer in a logical place (wasn't sure if in the .sty file or elsewhere to add) and ended up adding it as a PDF comment post-hoc. FWIW, Owen indicated that on the second page, immediately above or below the copyright, would be the best place.

**Comment by chantelwetzel-noaa** [comment]
I too had a similar struggle and ideally we will update the template to include this (with the ease of removal once the assessment is final).  I ended up putting it in file 01a.Rmd so it would come up first in the document after the outline.  I then added a section header to it as well so it would come up clearly in the outline as well: 

# Disclaimer{-}

_**These materials do not constitute a formal publication and are for information only. They are in a pre-review, pre-decisional state and should not be formally cited or reproduced. They are to be considered provisional and do not represent any determination or policy of NOAA or the Department of Commerce.**_

\pagebreak

Definitely not perfect but hopefully adequate for now.

**Comment by mkapur** [comment]
Thanks Chantel, that's a good workaround, and good point about "ease of removal" (less so if buried in the .sty). Ideally it could show up closer to the title page, but as long as it's somewhere.

**Comment by chantelwetzel-noaa** [comment]
@mkapur I should have also said congrats on fishing the update assessment!

**Comment by kellijohnson-NOAA** [comment]
532a96d implements a disclaimer by using
```
disclaimer: true
```
in the yaml header of 00a.Rmd. The default is to have the disclaimer turned on. You can set it to false or remove the line from 00a.Rmd if you want the citation instead of a disclaimer.

**Comment by iantaylor-NOAA** [comment]
Worked for me.
Thanks @chantelwetzel-noaa and @kellijohnson-NOAA for making this happen, and also providing instructions on how to retroactively apply it to existing documents.
![image](https://github.com/pfmc-assessments/sa4ss/assets/4992918/08f42e71-1140-4afc-beff-571b79111502)
