### ISSUE TITLE
how to use landscape tables

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/sa4ss#26]
Thanks to @mkapur for letting me know about her trials and tribulations with landscape tables. There are two methods one can take while writing markdown and wanting landscape pages to be intermixed with portrait pages.

1. include .tex files that contain the table code as @chantelwetzel-noaa did [here](https://github.com/chantelwetzel-noaa/dover_sole_2021/blob/181216d975e2e44edc700e489b2e792ffff3a85b/write_up/tex_tables/sensitivities2.tex) or
2. if you want to include the code in an .Rmd file then you need to follow the guidance provided [here](https://stackoverflow.com/questions/25849814/rstudio-rmarkdown-both-portrait-and-landscape-layout-in-a-single-pdf).

Eventually, I will include (2) in the sty file for anyone to use but I need more time to ensure that it doesn't lead to other problems if people also want to use (1).

**Comment by chantelwetzel-noaa** [comment]
Can we post what the original issue was?  I have not had any issues (probably just luck).  I created the landscape table link to in option 1 above using the table_format function as: 

```
t = table_format(x = out,
      caption = 'Sensitivities to changes in input data relative to the base model. The 
      data source listed has been removed for the sensitivity run.',
      label = 'sensitivities',
      longtable = TRUE,
      font_size = 9,
      landscape = TRUE,
      col_names = modelnames)

kableExtra::save_kable(t,
file = file.path(out.dir, "sensitivities.tex"))
```
This was done in a R code file summarizing all sensitivities using `r4ss`. This tex file is then included in the document via `\include`.  I have also done landscape in Rmd code chunks in a similar fashion.

**Comment by kellijohnson-NOAA** [comment]
I think the issue was having the \landscape call outside of a code chunk, i.e., in the markdown text. I think it depends on which version of pandoc you are using, [here](https://github.com/jgm/pandoc/issues/4667) they mention pandoc 2.2 is when changes were made.

**Comment by chantelwetzel-noaa** [comment]
Gotcha.  That is helpful thanks.  In my landscape table that are created in a code chunk I don't call landscape outside the code but rather use the table function to print out a landscape table.  However, I now can see is someone was taking a different approach that this would be a problem depending upon your version of pandoc.

**Comment by kellijohnson-NOAA** [comment]
We haven't had any problems since this so I am closing even though I have **NOT** added any documentation to the package. This issue will still be searchable though for longtable.
