### ISSUE TITLE
Survey data sections not showing up in the document outline

### ISSUE THREAD

**Issue by chantelwetzel-noaa** [pfmc-assessments/sa4ss#27]
If a section in the document uses pre-defined sa4ss.sty naming variables in a section header the section will show up in the document outline as blank (can see the branch in the outline but no title appears).  Here is an example of section naming that currently is not showing up:
```
### \acrlong{s-wcgbt}
```
The quick work around is to type out the survey name by hand (i.e. NWFSC West Coast Groundfish Bottom Trawl Survey); however, long-term we should figure out why this approach is not working and update the template accordingly.

**Comment by kellijohnson-NOAA** [comment]
Thank you for reporting this Chantel. Can you try one of the other options, like \gls{s-wcgbt} instead of \arclong{s-wcgbt}? I think it must be a rendering an order of operations thing where it doesn't have access to the list when making the TOC. I will google.

**Comment by kellijohnson-NOAA** [comment]
Looks like there is a lot of info [here](https://tex.stackexchange.com/questions/463684/glossaries-in-section-headings-without-shortening-after-toc) ... `to clear entries after the toc I can use \glsresetall That fixes the Problem. If the acronym comes up in the Text before, i use the \glsentryfull or \glsentrytext for the section`.

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa this was my fault because I was not including the acronym helper in the glossaries package. I have since pushed a change that should fix it.
