### ISSUE TITLE
update WCGBTS default text

### ISSUE THREAD

**Issue by mkapur** [pfmc-assessments/sa4ss#33]
In working on the sablefish update text, our team thought it might be good to include the following in the boilerplate background text associated with the WCGBTS:

Note that the WCGBT Survey is not permitted to access the Cowcod Conservation areas in southern California. Additionally, there were only two vessels used in 2019 and three in 2013, with one of the three that year unable to complete its survey pass due to a government shutdown. No survey occurred in 2020 due to the COVID-19 pandemic.

**Comment by kellijohnson-NOAA** [comment]
Thanks @mkapur et al. for the suggestion. I have added it to the list for the onboard 2021 assessment modifications to do list. Feel free to add other suggestions to either the main issue (#24), this issue, or a new issue. Thanks for using the template and for providing helpful feedback along the way.
