### ISSUE TITLE
array package in sty file

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/sa4ss#47]
```
\usepackage{array}
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}m{#1}}
```

Thanks @shcaba for pointing out that some decision tables need the array package. If you have any references (i.e., web links) that explained what the above was doing and you can share them here that would be great.

**Comment by shcaba** [comment]
The error I triggered was:
! Package array Error:  Illegal pream-token (C): `c' used.

This error had a general response to the issue:
https://tex.stackexchange.com/questions/513700/package-array-error-illegal-pream-token-c-c-used

The specific solution posted by Kelli I found in one of my other assessment document files.

**Comment by kellijohnson-NOAA** [comment]
The solution above just defines what the column type C means because it is not defined in the array package itself. This is not something that is specific to sa4ss but rather just a LaTeX formatting thing.
