### ISSUE TITLE
AFS species names list

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/sa4ss#58]
## **Problem**

Species names are inconsistent, e.g., "Pacific hake" versus "Pacific Hake", where the latter is formally used by the [AFS Names of Fishes](https://fisheries.org/books-journals/writing-tools/names-of-fishes-searchable-version/).

## **Proposal**

:shrug:

## **:cucumber:**

* [AFS Names of Fishes](https://fisheries.org/books-journals/writing-tools/names-of-fishes-searchable-version/) would be long and tedious to code up

**Comment by kellijohnson-NOAA** [comment]
I have been unable to find a digitized copy of the [pdf version of AFS species names](https://fisheries.org/wp-content/uploads/2015/11/Part-1.pdf) but I did find [FAO's database of species names](https://www.fao.org/faoterm/en/?defaultCollId=16) that can be [downloaded by clicking here](https://www.fao.org/fishery/static/ASFIS/ASFIS_sp.zip). Their rules for capitalization are different though. For example, whiting "North Pacific hake", which is different in two ways, (1) hake is lower case and (2) the inclusion of "North".

**Comment by iantaylor-NOAA** [comment]
As a team at NWFSC I don't think we actually reached consensus to use the AFS capitalization rules, so maybe this is an area where it's the author's responsibility.

**Comment by kellijohnson-NOAA** [comment]
No consensus so closing.
