### ISSUE TITLE
Switch to quarto ❓ 

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pfmc-assessments/sa4ss#65]
## **Problem**

quarto has been highlighted as the new best thing and we are using {bookdown} which relies on {rmarkdown} rather than {quarto}.

## **Proposal**

Stick with {bookdown} until 2025 assessments because currently there is nothing that we need in quarto that we cannot do in {bookdown} and everything is all set up. Second, I checked with @okenk regarding the functionality of the previewer/styled code in Rstudio and it works with Rmd files as well as qmd files.

## **Action items**

Please respond to this issue with a comment if you see a problem sticking with {rmarkdown} and {bookdown} rather than switching for 2023. Authors can feel free to use whatever best suits their needs and no one is constrained to using {sa4ss} for the 2023 cycle. I am tagging all known lead authors so if you do not have comments just un-assign yourself.

**Comment by brianlangseth-NOAA** [comment]
Are we reasonably confident that rmarkdown and bookdown will still work by the time we are building our reports?

**Comment by kellijohnson-NOAA** [comment]
@brianlangseth-NOAA 100%, the developers are committed to maintaining the packages just not adding new features.

**Comment by iantaylor-NOAA** [comment]
This was useful for me to gauge the level of support: https://community.rstudio.com/t/bookdown-evolution-in-response-to-quarto/133163/4.
I'm fine staying with the status-quo until 2025. We (especially @kellijohnson-NOAA) have enough on our plates related to data management and workflow that seems more important than any potential benefit of making this switch right away instead of in a year or two.

**Comment by melissamonk-NOAA** [comment]
I am ok with bookdown this cycle and think that most things we do this year can easily be translated to Quarto in the future. If there are aspects of the document that we know will not translate easily we should not invest too much time in those, i.e., if how we make the document accessible will change, we may consider doing all of the 508 compliance external to markdown.

**Comment by chantelwetzel-noaa** [comment]
I agree that using bookdown this next cycle will be fine. I am of similar mind to @iantaylor-NOAA that our plates are already very full and there is no need to add additional workload.

**Comment by kellijohnson-NOAA** [comment]
I can reopen this issue when we actually plan on switching.
