### ISSUE TITLE
Coast name

### ISSUE THREAD

**Issue by melissamonk-NOAA** [pfmc-assessments/sa4ss#9]
Another consideration in the for the coast element in the draft is that the area-specific assessments will probably need more detail included than just U.S. West Coast.  I'll likely want the northern vermilion assessment to read something like "...along the California Coast from Point Conception north"

**Comment by chantelwetzel-noaa** [comment]
Good point.  For copper I have started by specifying coast = "Washington US West" inside the draft function which then creates the title as: 

"...along the **Washington US West** Coast in 2020"

we may want to decide if we to decide whether we want to revise the pasted text after the coast input to include Coast by default or not.
